### ISSUE TITLE
HTML Output is Missing Quotes?

### ISSUE THREAD

**Issue by DanielGillett** [prjseal/Our.Umbraco.EditLink#1]
Hi Paul,

I hope I am putting this in the right place.

I was looking at my page source when I noticed the output HTML from the EditLink is missing a space (**inner"style=**) and some quotes around the **style attribute**.  I haven't modified anything or changed any of the default attributes. 

here's the output...

`<a  href ="/umbraco#/content/content/edit/1235" target="_blank" class="edit-link-inner"style=color:#fff;background-color:#1b264f;padding:10px;font-size:16px;border-radius:6px;>`

A very handy tool. Thank you for building it.  ...my mother doesn't get as lost switching from the front-end to the back end. lol

Best,
Daniel

**Comment by stefankip** [comment]
I came here to report the same thing.
Also there are some extra spaces: `<a  href ="/umbraco#/content/content/edit/1060"`

**Comment by prjseal** [comment]
I've just released the fix for this. Thanks both for raising it.

**Comment by stefankip** [comment]
And thank you for sharing this nice package with us! :-) #h5yr
